name: Deploy to FLY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load .mautic_env variables
      run: |
        set -a
        source .mautic_env
        set +a
        echo "MAUTIC_PORT=${MAUTIC_PORT}" >> $GITHUB_ENV

    - name: Check required secrets
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        MAUTIC_PASSWORD: ${{ secrets.MAUTIC_PASSWORD }}
      run: |
        echo $FLY_API_TOKEN
        echo $MAUTIC_PASSWORD
        error_missing_secrets=()
        check_secret() {
          if [ -z "${!1}" ]; then
            error_missing_secrets+=("$1")
          fi
        }

        check_secret "FLY_API_TOKEN"
        check_secret "MAUTIC_PASSWORD"

        if [ ${#error_missing_secrets[@]} -ne 0 ]; then
          echo "Error: Missing required secrets: ${error_missing_secrets[*]}"
          exit 1
        fi

    - name: Install Flyctl
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="/home/runner/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"

    # Log into Fly.io
    - name: Fly.io Authentication
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth token $FLY_API_TOKEN

    - name: fly launch mautic-db no-deploy
      run: |
        flyctl launch --name mautic-db --no-deploy
      
